@startuml

'autonumber

actor User as Usr
participant "Claude Desktop" as CD
participant "Anthropic Remote Server \n( LLM - Claude 1 / Claude 2)" as AnthropicServer
participant "Postgres Database \n or any other external tool" as DB

Usr --> CD: a) Creates <b>MCP configuration</b> \n in claude_desktop_config.json
CD --> AnthropicServer: b) Save <b>MCP configuration</b>
note right
stores <b>MCP configuration</b>
for connecting to Postgres
end note
Usr -> CD: 1. Submit text query
CD -> AnthropicServer: 2. Send text query
AnthropicServer -> AnthropicServer: 3. Transform text query \n into SQL
AnthropicServer -> DB: 4. Execute SQL query
DB -> AnthropicServer: 5. Return results
AnthropicServer -> CD: 6. Return obtained results
CD -> Usr: 7. Display results

@enduml